import type { Rule, Finding, FileContext, ProjectContext } from '../types.js'
import { isCommentLine } from '../utils/patterns.js'

const HALLUCINATED_APIS: { pattern: RegExp; fix: string }[] = [
  { pattern: /\.flatten\s*\(/, fix: 'Use .flat() instead of .flatten()' },
  { pattern: /\.contains\s*\(/, fix: 'Use .includes() instead of .contains()' },
  { pattern: /\.substr\s*\(/, fix: 'Use .substring() or .slice() instead of deprecated .substr()' },
  { pattern: /\.trimLeft\s*\(/, fix: 'Use .trimStart() instead of deprecated .trimLeft()' },
  { pattern: /\.trimRight\s*\(/, fix: 'Use .trimEnd() instead of deprecated .trimRight()' },
  { pattern: /response\.body\.json\s*\(/, fix: 'Use response.json() instead of response.body.json()' },
  { pattern: /fetch\.abort\s*\(/, fix: 'Use AbortController instead of fetch.abort()' },
  { pattern: /\.isArray\s*\(\s*\)/, fix: 'Array.isArray() is static — use Array.isArray(value)' },
  { pattern: /\.hasOwnProperty\s*\(/, fix: 'Use Object.hasOwn() instead of .hasOwnProperty()' },
]

export const hallucinatedApiRule: Rule = {
  id: 'hallucinated-api',
  name: 'Hallucinated API',
  description: 'Detects non-existent or deprecated JavaScript/DOM APIs often generated by AI',
  category: 'ai-quality',
  severity: 'warning',
  fileExtensions: ['ts', 'tsx', 'js', 'jsx'],

  check(file: FileContext, _project: ProjectContext): Finding[] {
    const findings: Finding[] = []

    for (let i = 0; i < file.lines.length; i++) {
      if (isCommentLine(file.lines, i, file.commentMap)) continue
      const line = file.lines[i]

      for (const { pattern, fix } of HALLUCINATED_APIS) {
        const match = pattern.exec(line)
        if (match) {
          findings.push({
            ruleId: 'hallucinated-api',
            file: file.relativePath,
            line: i + 1,
            column: match.index + 1,
            message: fix,
            severity: 'warning',
            category: 'ai-quality',
          })
        }
      }
    }

    return findings
  },
}
